services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: atriarchy
      POSTGRES_PASSWORD: atriarchy_secret
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  s3:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: atriarchy_key
      MINIO_ROOT_PASSWORD: atriarchy_secret
      MINIO_DEFAULT_BUCKETS: atriarchy:download,documenso:download
    volumes:
      - s3:/bitnami/minio/data

  maildev:
    image: maildev/maildev:latest
    ports:
      - 1025:1025 # SMTP server
      - 3080:80 # Web UI
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 80

  documenso-db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: documenso
      POSTGRES_PASSWORD: documenso
      POSTGRES_DB: documenso
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U documenso_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - documenso-db:/var/lib/postgresql/data

  documenso:
    image: documenso/documenso:latest
    depends_on:
      documenso-db:
        condition: service_healthy
    environment:
      PORT: 4001
      NEXTAUTH_URL: http://localhost:4001
      NEXTAUTH_SECRET: secret
      NEXT_PUBLIC_WEBAPP_URL: http://localhost:4001
      NEXT_PUBLIC_MARKETING_URL: https://documenso.com
      NEXT_PRIVATE_DATABASE_URL: postgres://documenso:documenso@documenso-db:5432/documenso
      NEXT_PRIVATE_DIRECT_DATABASE_URL: postgres://documenso:documenso@documenso-db:5432/documenso
      NEXT_PRIVATE_ENCRYPTION_KEY: ICANT
      NEXT_PRIVATE_SECONDARY_ENCRYPTION_KEY: ICANT2
      NEXT_PRIVATE_SMTP_TRANSPORT: smtp-auth
      NEXT_PRIVATE_SMTP_HOST: maildev
      NEXT_PRIVATE_SMTP_PORT: 1025
      NEXT_PRIVATE_SMTP_FROM_NAME: Documenso
      NEXT_PRIVATE_SMTP_FROM_ADDRESS: no-reply@test.atriarchy.studio
      NEXT_PUBLIC_UPLOAD_TRANSPORT: s3
      NEXT_PRIVATE_UPLOAD_ENDPOINT: http://s3:9000
      NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE: "true"
      NEXT_PRIVATE_UPLOAD_REGION: us-east-1
      NEXT_PRIVATE_UPLOAD_BUCKET: documenso
      NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID: atriarchy_key
      NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY: atriarchy_secret
      # this is a test cert dw:
      NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS: MIIKSQIBAzCCCg8GCSqGSIb3DQEHAaCCCgAEggn8MIIJ+DCCBK8GCSqGSIb3DQEHBqCCBKAwggScAgEAMIIElQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQI2JYUXahT+H8CAggAgIIEaMNzUPEe+11DT0GhNw6O+4cKYCZu72ZAzTA8f39pgLcDCka0dMuhFnOkC0mFIY7toNhD7KRm3zFW55npgGbVZO6o5luOUtI7evxZJBQXyStng5Yy1eHTdm2i6Pp+1qo2WAiWyVZuaHnozh+YMKAQFBDzSeT7pfMEcJ4+V4COIhC8JXJaEmH4scOUPzDhd4+MQza5vLU5QMWourSfYLLW0hDvFnQTef9ssZJiZb8pdnadH381xBoKWvTsu1YKKKVcgB9JfXW4By4fKvD0KSHY7+nXc/4LBQOWHCYA4U7q5Q4UHsXyYvk9HTcunRGRYi83slRgheoNYrTAbJ8fg1+pBMghXYjW6LLzxYMZgM0YrIh3aky8JNjg6gEYW9SHxuJCTk4RzcXeKbXIgJgjuTNpDT9nmaWN9VjRNdBj/jorQTZoEu2ed04w/nzkcn3kGYs0R7WQk1oP5Q+ut45wUuRkoDNBmV8xEHnbQUGI6OqX9XgBxdmdAvVrIuX9WaJYW/O5tMU6vowaKX8Iv5r9K343Tl6EG4J+PjNVO5fmqYJ/grQvuvyaRifXPYt0Pca/l9qNsYdjhl4f4OyrTPyNGWx00EwV+G4+zfVpmmHJl2ZAiYiwkFx3wOSpeJGLHbPNyR3B0YHWwYTkTtk0gIpfpd/iAtoDNDSaGgDtDUQrprwzUrsEK9fhdo9QMgMmGTZXGgqjL8CAHltwOJhMB/RjMxyvAsZ6BQC3uXlhFHSzUfKrPpGd6r/QUNi/s4G8Stj+dDMlY+g+Oj9gq3Ud5J10w/LV32iqqj+DGUnZf3b4x6hE42F2ICLuaCazqlReGaG3aULSzjUqdbo6N74H2a7n0DZCoJK1rWHLmgZjKXa6SvLyiZ+DpwNN7uClfAtkQwamcWfTP8xavZSCiABzIb8MrX2pVRK+7WyZmbZNqPghKdptRZIY+utN8NQ2l0MwHyTtPxuOZ/jkZuTuH2wt1hkeIJBtYOM/i0DEDHwhSG7Xh/tauvm+Q7tC57MhFnF4AM8Fir2W+FuDATVsDqFwFH+MlBNXn/fA/XQIXYWBcpn1OuHUVy7btepNp65H3hhHcSAo4lYKx638jbe5H88WTp6T2jYiwA3DrVm6dhw5P0TIWueE4U+ZMCBNA8q3vWmOVM9S357B1UocBI0bW6amXmnU8dUC/B4Run/8utx82qeCHXrLKwzzic+fh6kHIJfC0ZyUfZj566an/I/OFBC5JNy0JzCVtXJlQd8wtSbc1K2xSXn03ViedQxqhngLxEfrHOUOHJvgobGNnyKyjkG1QZ0aaUccXQc5X0yOOyfjE7Dhwdbr6XVHHgvefvbfs71XMjXFrVIvTZXXwyHZpl6X4fb4GF3DhoE6HS6aPwl4EjHAwLCmZXUjUkxWIPSHqgvPFxD/ccDZ2ZwKLdM4nKXrHOhD9ZVCZcO2LHI8ICj3kpnzvFfHhthiz7Y2NM3oJ/Qjjv867CG+n7zW7P4nG84ew1+48mqfWrDoOQaTRdiXYzCCBUEGCSqGSIb3DQEHAaCCBTIEggUuMIIFKjCCBSYGCyqGSIb3DQEMCgECoIIE7jCCBOowHAYKKoZIhvcNAQwBAzAOBAjFp46Y65GT8wICCAAEggTIYL/SLEjHWs2k7Cyd5IOnMlaGd1ebzbRUMWS+Mdz7SUmZlG6ulBFLeCaDlDXVPY0Sb1nx0PgxK0V1d7+8j6+m3FuQ7aez7X/MLDaS9ALC6JXPH6ICFE/wzpv8Ij7uuMqwU4C/KGsOMt5bPM42SqdEdsKdNZJEFkBq70M2Waro5HfYP8KCratijjUaIv+U6FK9s7LHG/DmDfF7x3ud3KE930vJU1evzv9kCnpbYmTe6xVgNLGC8Lr31X09z9q63SdzBmst0Mr2T+IExFm3WHxWGC4MCDNn8DaoMB07Jut3bfGYCE00ggi2+9ABWy+IW3mQIH8xAdgMeo099OBOUBe8FJVbMUfO+IOa/zqtuytfEMeFevAGo6bEcfkfHOiNU+TaMJJfYnVVIApTRt2kA5z/Rypji+lS+eoPUNI+ICp5Xe8JHH4aUcs5tx1czJ2E8RKvZVQtAIs+iY4DPtvqXj/2y1MjjjBK9Q4hyvKpIm9P1udHSh+zFfyYDh9gNrm8AJNyeDdiQ2GuYVSJS98gdg+QgHuJdNOvGHcagvS0l9/4HPZ8kDPyhK71aXjAU5/iKOzqHQ/ndh+R/zUPGOBtG1aMzBYz9d8jBBD9ujqxLcrMK0RpbtGA0B0l7f6Pk/AYBgzSDQlnwpU5x2CH9VWd7hC9Px+8j2IThEPjeCm97fVdvkcr4vFtnmJZGI/s5B2LCSeU0GSb1Je/eP5nI2jjjll1p30shMcfMJ8WP9+h8ZdJLXeLzYMCuSiWTvyLpXGxAKZXNOQHqbUrUbpQ7Ry9rAbfcNKr4H59AgHF58BxdMzapcA0YRgN0/k2PrbjJtdQEkFgS8QhxkEBJUgvWrcC8oF9K/fC0j2LeNeBmtZ2Hjn5Glzg0RS3Nev35RhCce2+81tke1U/1ZHUaR4yf/qbQ0ult0Eg0bDxfB+3YfzVs7Q7W9UmxQKchzcNNPMFWy+owmwEnjnFB5XmM95V/hfe98I2npR571iIA8kbaPH/D13fN56r/n7wPnncHr5+Xh2QwUzoPDRcbC7SftPX2pWvMR7N8Vi6AnDV6DxeufcpBiWilSMaKFw2nEUpPChtZq4Ez4wZMBA2/TMtQ909jpN5lpIrVFXWD3Jd+stK9Y2XkXkQnCpNesoipnlpTutUotorzvp+tiqcnKLJsW0WGVuWkR8XoX/ybwXloxwwuFJfMOpZVb+5zZUQPNFo1LbQ4u3Omf6ij0y31vxVZ1c7WaXXhzA4sHwlxPwQAQOJVTJImpynUKKxsWzSaT/2vESh5JPnCdGdS0KAd2xhi5zho6v0RFb2IUgx0WDQytjqfHuZXUoY7X7k1T5jN3fnSL8OYN1LlzhRSbyjpwZ6y1u17SId7RODEwr3YzBNUq9GqhiKAVkVHGYYYQcJoSCCES5mnFmoiJOZB0A3BKZQb64gIw7LJN38yY96JjNqonckpvRIfGc3fS3tghgqTMzLsan5GVYLV2PyddYapZyb/z6UnOWNTZq5iDpA515AutHNmBgohOog901GR5/yoBqDyWCIysqM/TL+TTCA3jm2qoJesE+jJq8PyNr/0df/9ZFbw0Re48aImLSKGWf4hcxxqAIJSl2sZX9rKt0QdhOziZfx1N8lUpeodcVH3YzTj8eMMSUwIwYJKoZIhvcNAQkVMRYEFIek82Xr6dmE3LM+fnlH/Aj+1Mg+MDEwITAJBgUrDgMCGgUABBSL/qFIWkj1PsW6ToFJpuCtCJaTNQQIDw/Fpp+LIqcCAggA
    ports:
      - 4001:4001

volumes:
  db:
  s3:
  documenso-db:
